/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as EventsRouteImport } from './routes/events'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as ConnectBelongGroupsRouteImport } from './routes/connect.belong-groups'
import { Route as ConnectBlackBusinessDirectoryRouteImport } from './routes/connect.black-business-directory'
import { Route as ConnectMinistriesRouteImport } from './routes/connect.ministries'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectBelongGroupsRoute = ConnectBelongGroupsRouteImport.update({
  id: '/connect/belong-groups',
  path: '/connect/belong-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectBlackBusinessDirectoryRoute =
  ConnectBlackBusinessDirectoryRouteImport.update({
    id: '/connect/black-business-directory',
    path: '/connect/black-business-directory',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConnectMinistriesRoute = ConnectMinistriesRouteImport.update({
  id: '/connect/ministries',
  path: '/connect/ministries',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRoute
  '/messages': typeof MessagesRoute
  '/visit': typeof VisitRoute
  '/connect/belong-groups': typeof ConnectBelongGroupsRoute
  '/connect/black-business-directory': typeof ConnectBlackBusinessDirectoryRoute
  '/connect/ministries': typeof ConnectMinistriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRoute
  '/messages': typeof MessagesRoute
  '/visit': typeof VisitRoute
  '/connect/belong-groups': typeof ConnectBelongGroupsRoute
  '/connect/black-business-directory': typeof ConnectBlackBusinessDirectoryRoute
  '/connect/ministries': typeof ConnectMinistriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRoute
  '/messages': typeof MessagesRoute
  '/visit': typeof VisitRoute
  '/connect/belong-groups': typeof ConnectBelongGroupsRoute
  '/connect/black-business-directory': typeof ConnectBlackBusinessDirectoryRoute
  '/connect/ministries': typeof ConnectMinistriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/events'
    | '/messages'
    | '/visit'
    | '/connect/belong-groups'
    | '/connect/black-business-directory'
    | '/connect/ministries'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/events'
    | '/messages'
    | '/visit'
    | '/connect/belong-groups'
    | '/connect/black-business-directory'
    | '/connect/ministries'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/events'
    | '/messages'
    | '/visit'
    | '/connect/belong-groups'
    | '/connect/black-business-directory'
    | '/connect/ministries'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EventsRoute: typeof EventsRoute
  MessagesRoute: typeof MessagesRoute
  VisitRoute: typeof VisitRoute
  ConnectBelongGroupsRoute: typeof ConnectBelongGroupsRoute
  ConnectBlackBusinessDirectoryRoute: typeof ConnectBlackBusinessDirectoryRoute
  ConnectMinistriesRoute: typeof ConnectMinistriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/belong-groups': {
      id: '/connect/belong-groups'
      path: '/connect/belong-groups'
      fullPath: '/connect/belong-groups'
      preLoaderRoute: typeof ConnectBelongGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/black-business-directory': {
      id: '/connect/black-business-directory'
      path: '/connect/black-business-directory'
      fullPath: '/connect/black-business-directory'
      preLoaderRoute: typeof ConnectBlackBusinessDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/ministries': {
      id: '/connect/ministries'
      path: '/connect/ministries'
      fullPath: '/connect/ministries'
      preLoaderRoute: typeof ConnectMinistriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EventsRoute: EventsRoute,
  MessagesRoute: MessagesRoute,
  VisitRoute: VisitRoute,
  ConnectBelongGroupsRoute: ConnectBelongGroupsRoute,
  ConnectBlackBusinessDirectoryRoute: ConnectBlackBusinessDirectoryRoute,
  ConnectMinistriesRoute: ConnectMinistriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
